## Heuristic Approach

Use it when you have scarcity of data.

## Can use pre built APIs

## Machine Learning Approach

**Dataset** => `IMDB 50K movie` => 50k movie sentiments

In [1]:
import numpy as np
import pandas as pd

### Download the dataset

Use this link to download the dataset=> https://www.kaggle.com/datasets/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews

In [2]:
temp_df = pd.read_csv("/kaggle/input/imdb-dataset-of-50k-movie-reviews/IMDB Dataset.csv")

In [3]:
df = temp_df.iloc[:10000]

In [4]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

### Clean the data

In [5]:
df['review'][1]

'A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well done.'

In [6]:
df['sentiment'].value_counts()

sentiment
positive    5028
negative    4972
Name: count, dtype: int64

In [7]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [8]:
df.duplicated().sum()

17

In [9]:
df.drop_duplicates(inplace=True)

/tmp/ipykernel_37/3006716147.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)

In [10]:
df.duplicated().sum()

0

### Basic Processing
- Remove tags
- Lowercase
- Remove stopwords

In [11]:
import re
def remove_tags(raw_text):
    cleaned_text = re.sub(re.compile('<.*?>'), '', raw_text)
    return cleaned_text

In [12]:
df['review'] = df['review'].apply(remove_tags)

/tmp/ipykernel_37/2336150696.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(remove_tags)

In [13]:
df

                                                 review sentiment
0     One of the other reviewers has mentioned that ...  positive
1     A wonderful little production. The filming tec...  positive
2     I thought this was a wonderful way to spend ti...  positive
3     Basically there's a family where a little boy ...  negative
4     Petter Mattei's "Love in the Time of Money" is...  positive
...                                                 ...       ...
9995  Fun, entertaining movie about WWII German spy ...  positive
9996  Give me a break. How can anyone say that this ...  negative
9997  This movie is a bad movie. But after watching ...  negative
9998  This is a movie that was probably made to ente...  negative
9999  Smashing film about film-making. Shows the int...  positive

[9983 rows x 2 columns]

In [14]:
df['review'] = df['review'].apply(lambda x:x.lower())

/tmp/ipykernel_37/740760900.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(lambda x:x.lower())

In [15]:
from nltk.corpus import stopwords
sw_list = stopwords.words('english')
df['review'] = df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))

/tmp/ipykernel_37/4184252231.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))

In [16]:
df

                                                 review sentiment
0     one reviewers mentioned watching 1 oz episode ...  positive
1     wonderful little production. filming technique...  positive
2     thought wonderful way spend time hot summer we...  positive
3     basically there's family little boy (jake) thi...  negative
4     petter mattei's "love time money" visually stu...  positive
...                                                 ...       ...
9995  fun, entertaining movie wwii german spy (julie...  positive
9996  give break. anyone say "good hockey movie"? kn...  negative
9997  movie bad movie. watching endless series bad h...  negative
9998  movie probably made entertain middle school, e...  negative
9999  smashing film film-making. shows intense stran...  positive

[9983 rows x 2 columns]

In [17]:
X = df.iloc[:,0:1]
y = df['sentiment']

In [18]:
X

                                                 review
0     one reviewers mentioned watching 1 oz episode ...
1     wonderful little production. filming technique...
2     thought wonderful way spend time hot summer we...
3     basically there's family little boy (jake) thi...
4     petter mattei's "love time money" visually stu...
...                                                 ...
9995  fun, entertaining movie wwii german spy (julie...
9996  give break. anyone say "good hockey movie"? kn...
9997  movie bad movie. watching endless series bad h...
9998  movie probably made entertain middle school, e...
9999  smashing film film-making. shows intense stran...

[9983 rows x 1 columns]

In [19]:
y

0       positive
1       positive
2       positive
3       negative
4       positive
          ...
9995    positive
9996    negative
9997    negative
9998    negative
9999    positive
Name: sentiment, Length: 9983, dtype: object

In [20]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y = encoder.fit_transform(y)

In [21]:
y

array([1, 1, 1, ..., 0, 0, 1])

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 1)

In [23]:
X_train.shape, y_train.shape

((7986, 1), (7986,))

### Applying BOW

In [24]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()

X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

In [25]:
X_train_bow.shape

(7986, 48282)

48282 is the vector size which mean our vocabulary had 48282 diff words

In [26]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

gnb.fit(X_train_bow, y_train)

GaussianNB()

In [27]:
y_pred = gnb.predict(X_test_bow)

from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(y_test, y_pred)

0.6324486730095142

In [28]:
confusion_matrix(y_test, y_pred)

array([[717, 235],
       [499, 546]])

In [29]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()

rf.fit(X_train_bow, y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test, y_pred)

0.8542814221331998

In [30]:
cv = CountVectorizer(max_features=3000)

X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

rf = RandomForestClassifier()

rf.fit(X_train_bow, y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test, y_pred)

0.8362543815723585

In [31]:
## trigram (3-ngram)
cv = CountVectorizer(ngram_range=(1, 3), max_features=5000)

X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

rf = RandomForestClassifier()

rf.fit(X_train_bow, y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test, y_pred)

0.8432648973460191

### Using TF-IDF

In [33]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

X_train_tfidf = tfidf.fit_transform(X_train['review']).toarray()
X_test_tfidf = tfidf.transform(X_test['review'])

rf = RandomForestClassifier()

rf.fit(X_train_tfidf, y_train)
y_pred = rf.predict(X_test_tfidf)
accuracy_score(y_test, y_pred)

0.8397596394591887

### Using Word2Vec

- Pretrained
- Train a new Word2Vec on your data

We will use AvgWord2Vec

We will use AvgWord2Vec

In [34]:
import gensim
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [35]:
story = []
for doc in df['review']:
    raw_sent = sent_tokenize(doc)
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

In [37]:
model = gensim.models.Word2Vec(window=10,
                               min_count=2)

In [38]:
model.build_vocab(story)

In [39]:
model.train(story, total_examples=model.corpus_count, epochs=model.epochs)

(5849752, 6186875)

In [40]:
def document_vector(doc):
    # remove out-of-vocabulary words
    doc = [word for word in doc.split() if word in model.wv.index_to_key]
    return np.mean(model.wv[doc], axis=0)

In [42]:
document_vector(df['review'].values[0])

array([ 0.05107558,  0.3562648 ,  0.25611174,  0.01978634, -0.07301587,
       -0.57774156,  0.14161527,  0.8745158 , -0.18971127, -0.20247556,
       -0.2620996 , -0.59390354, -0.05361619,  0.29190558,  0.20483427,
       -0.269933  ,  0.14897363, -0.5897457 , -0.07795261, -0.64933753,
       -0.00091463,  0.12285287,  0.19689298, -0.22969611, -0.17903736,
       -0.1264303 , -0.14889067, -0.21785018, -0.36580136, -0.05386831,
        0.42872563,  0.0347767 , -0.09880253, -0.19572769, -0.42132843,
        0.35418257,  0.05775705, -0.3174773 , -0.12937483, -0.7404878 ,
        0.13772076, -0.21408065, -0.17960668, -0.0077766 ,  0.39701518,
       -0.13934879, -0.4576701 , -0.23035228,  0.06814238,  0.330047  ,
        0.12543198, -0.33357015, -0.3675997 , -0.15857801, -0.40038255,
        0.07772805,  0.35995364,  0.17543572, -0.2804684 ,  0.04534315,
       -0.04763209,  0.1542913 , -0.21438015, -0.00599006, -0.35443497,
        0.426691  , -0.03179454,  0.05995964, -0.5542025 ,  0.30094013,
       -0.11038333,  0.20997089,  0.39542595, -0.04559628,  0.47951362,
        0.0102274 ,  0.14068374, -0.20652352, -0.31736264,  0.12706318,
       -0.2770758 , -0.00992443, -0.4854293 ,  0.5062363 , -0.08821428,
       -0.2067526 ,  0.08355494,  0.20911112,  0.3193125 ,  0.18054582,
        0.28938836,  0.11392815, -0.01479179,  0.10712562,  0.5383041 ,
        0.09473017,  0.2940515 , -0.3357406 ,  0.21179326,  0.01343211],
      dtype=float32)

In [43]:
from tqdm import tqdm

X = []
for doc in tqdm(df['review'].values):
    X.append(document_vector(doc))

100%|██████████| 9983/9983 [03:07<00:00, 53.36it/s]

In [44]:
X = np.array(X)
X.shape

(9983, 100)

In [45]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
y = encoder.fit_transform(df['sentiment'])

y

array([1, 1, 1, ..., 0, 0, 1])

In [46]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [49]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

mnb = GaussianNB()
mnb.fit(X_train, y_train)

y_pred = mnb.predict(X_test)

accuracy_score(y_test, y_pred)

0.7240861291937907

In [51]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()

rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)

accuracy_score(y_test, y_pred)

0.7816725087631448